---
title: "Talks"
---

### 2025

**Pins and Pistons: Gender and Patenting during the French Industrialization. Final Seminar.**
Final seminar, Presenter, Economic History Department, LUSEM, Lund University, December 5 2025.
Discussants: [Maria Stanfors](https://portal.research.lu.se/en/persons/maria-stanfors/) and [Alessandro Nuvolari](https://www.santannapisa.it/en/alessandro-nuvolari)
Main supervisor: [Faustine Perrin](https://faustine-perrin.com/)
Co-supervisor: [Josef Taalbi](https://joseftaalbi.com)

Click here for the [slides](talks\final_seminar.html)

</br>

**Structuring and Linking Individual-Level Data through Machine Learning**
Conference session, Presenter and Organizer, The Application of Cutting-edge Technology to Economic History Research, WEHC 2025, Lund University, Sweden, July 28 2025.

Click here for the [slides](talks\machine-Learning-economic-history-2025-Youssouf-Merouani.pdf)


</br>

**Origins and Trajectories of French Women Inventors in the Long Nineteenth Century**
Conference session, Organizer and Panelist, Leading Change to Gender Equality: Female Pioneers in Patenting and Innovative Activities, WEHC 2025, Lund University, Sweden, July 30 2025.

Co-author, Co-organizer and lead presenter: [Faustine Perrin](https://faustine-perrin.com/)

### 2024

**Tailoring ML Tools for Economic History Research: The case of HISCO.**
Presenter, Workshop in Machine Learning, organized by Prof. Kerstin Enflo, Economic History Department, LUSEM, Lund University, January 23 2024.

</br>

### 2023

**Innovation and Gender during Industrialization. Midway Seminar: The case of patenting activity in France 1791-1913.**
Midway seminar, Presenter, Economic History Department, LUSEM, Lund University, November 27 2023.
Discussant: [Josef Taalbi](https://joseftaalbi.com)
Supervisor: [Faustine Perrin](https://faustine-perrin.com/)

Click here for the [slides](talks\midway_seminar.html)

</br>

**Gender and innovation networks during French industrualization**
Conference session, Presenter, European Historical Economics Society Conference, Vienna University of Economics and Business, Austria, September 2 2023.

</br>

**Women Inventors. An Exploration of French Patenting Activities, 1791–1900**
Conference session, European Historical Economics Society Conference, Vienna University of Economics and Business, Austria, September 2 2023.
Co-author and lead presenter: [Faustine Perrin](https://faustine-perrin.com/)

</br>

**Women Inventors. An Exploration of French Patents, 1791–1900**
Conference session, Presenter, V. Kongress für Wirtschafts- und Sozialgeschichte, Leipzig, Germany,  March 31 2023.
Co-author: [Faustine Perrin](https://faustine-perrin.com/)

### 2022

**Women Inventors. An Exploration of French Patents, 1791–1900**
Presenter and Attendee, Residential Training Course for PhD Students in Economic and/or Social History, Radcliffe House, University of Warwick,  U.K.,  30 November – 3 December 2022.
Co-author: [Faustine Perrin](https://faustine-perrin.com/)

</br>

**Women Inventors. An Exploration of French Patents, 1791–1900**
Conference session, Presenter, World Economic History Paris, France,  July 27 2023.
Co-author: [Faustine Perrin](https://faustine-perrin.com/)

### 2021

**What does it take to survive on an island?: The relationship between firm survival and contextual factors in a peripheral region**
Lead author and Presenter, RENT 2021, Turku, Finland, November 18, 2021
Co-authors: Marcus Box, Tommy Larsson Segerlind, Paulina Rytkönen