---
title: "Teaching"
---

### Business and Society - A Dynamic Perspective

- **Institution**: LUSEM, Lund University
- **Dates**: Fall 2023
- **Course Level**: Undergraduate course, 7.5 credits
- **Your Role**: Seminar Teacher
- **Number of Students**: 40
- **Course Description**: This course investigates the development and influence of corporations in capitalist societies, examining their origins, evolution, and impact on society through a historical lens from antiquity to the present. My teaching activity in this course involves providing feedback on students' presentations and demonstrating how they can further deepen their analysis in the future.

### Economic Change, Labour Market and the Population

- **Institution**: LUSEM, Lund University
- **Dates**: Spring 2023 - Spring 2024
- **Course Level**: Undergraduate course, 7.5 credits
- **Your Role**: Lecturer
- **Number of Students**: 40
- **Course Description**: The course examines the development of Swedish labour policy in general during the post-war period. Particular attention is paid to the fundamental changes that have occurred from the 1970s onwards in the functioning of the labour market, the welfare system, and the economy as a whole. My module consists of three lectures and a seminar focusing on women in the labour market.

### Research Design, Methods and Data Collection

- **Institution**: LUSEM, Lund University
- **Dates**: Spring 2023 - Spring 2024
- **Course Level**: Undergraduate course, 15 credits
- **Your Role**: Lecturer
- **Number of Students**: 40-70
- **Course Description**: The course aims to provide students with foundational knowledge in research design, methods, data collection, and implementation. The course is divided into three primary modules. My module consists of three lectures and a seminar on quantitative research in Economics and Economic History.

### Entrepreneurship: Context, Actors and Process

- **Institution**: Södertörn University
- **Dates**: Fall 2020 - Fall 2023
- **Course Level**: Undergraduate course, 7.5 credits
- **Your Role**: Guest Lecturer
- **Number of Students**: 45-50
- **Lecture Description**: This guest lecture is based on my master's thesis. I use the thesis as a foundation to explain what context is, and how context is important for entrepreneurial opportunities, challenges, processes, and activities. Finally, I teach the students concrete ways and tools to capture and measure different aspects of context.
